// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cityScope.NET.Server.Persistence;

#nullable disable

namespace cityScope.NET.Server.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231106112458_add-Categories")]
    partial class addCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 654, DateTimeKind.Local).AddTicks(7699),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 654, DateTimeKind.Local).AddTicks(8046),
                            MainCategoryId = 10,
                            Price = 3593.49m,
                            Title = "Small Wooden Gloves",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(588),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(667),
                            MainCategoryId = 5,
                            Price = 9562.12m,
                            Title = "Awesome Wooden Car",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/table.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(701),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(736),
                            MainCategoryId = 4,
                            Price = 4620.16m,
                            Title = "Ergonomic Concrete Soap",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/tv.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(754),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(790),
                            MainCategoryId = 10,
                            Price = 5168.30m,
                            Title = "Intelligent Cotton Pizza",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/table.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(806),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(839),
                            MainCategoryId = 8,
                            Price = 1467.77m,
                            Title = "Licensed Metal Hat",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/table.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(856),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(888),
                            MainCategoryId = 3,
                            Price = 4743.74m,
                            Title = "Handcrafted Fresh Bike",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(904),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(932),
                            MainCategoryId = 3,
                            Price = 4473.45m,
                            Title = "Intelligent Soft Sausages",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(948),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(976),
                            MainCategoryId = 1,
                            Price = 3223.27m,
                            Title = "Sleek Granite Soap",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(992),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(1063),
                            MainCategoryId = 1,
                            Price = 3635.23m,
                            Title = "Sleek Plastic Soap",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(1080),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2023, 11, 6, 12, 24, 58, 655, DateTimeKind.Local).AddTicks(1107),
                            MainCategoryId = 3,
                            Price = 3014.20m,
                            Title = "Sleek Cotton Bike",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/tv.jpg",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MainCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jewelery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Outdoors"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jewelery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Outdoors"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Automotive"
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Uniqueness", "Email");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 6, 12, 24, 58, 650, DateTimeKind.Local).AddTicks(7508),
                            Email = "example@example.com",
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTimeLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = new byte[] { 176, 72, 184, 74, 45, 228, 84, 23, 181, 59, 28, 170, 215, 223, 123, 109, 235, 224, 34, 251, 241, 49, 235, 201, 248, 124, 50, 229, 123, 137, 177, 235, 154, 66, 34, 9, 183, 140, 167, 160, 69, 2, 135, 233, 155, 166, 131, 103, 10, 147, 97, 26, 47, 1, 237, 25, 18, 54, 89, 159, 115, 33, 175, 114 },
                            PasswordSalt = new byte[] { 178, 197, 164, 125, 77, 4, 228, 180, 221, 218, 22, 192, 207, 245, 72, 24, 118, 34, 22, 153, 35, 208, 205, 132, 131, 22, 154, 95, 221, 64, 163, 254, 102, 57, 208, 240, 138, 172, 244, 197, 167, 198, 92, 157, 228, 172, 206, 184, 98, 28, 147, 69, 170, 145, 67, 26, 16, 52, 62, 231, 130, 52, 102, 55, 186, 177, 153, 121, 249, 230, 80, 74, 123, 89, 117, 121, 64, 214, 214, 45, 21, 252, 228, 11, 230, 67, 79, 175, 182, 2, 59, 229, 13, 183, 185, 156, 130, 93, 189, 136, 216, 125, 118, 143, 201, 175, 175, 214, 45, 215, 17, 145, 165, 90, 47, 234, 90, 20, 5, 104, 246, 236, 8, 85, 166, 157, 84, 121 },
                            isBlocked = false
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("cityScope.NET.Server.Domain.Entities.MainCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("MainCategoryId");

                    b.HasOne("cityScope.NET.Server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
