// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cityScope.NET.Server.Persistence;

#nullable disable

namespace cityScope.NET.Server.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230629111704_editUserTableToUniqueEmail")]
    partial class editUserTableToUniqueEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(1756),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(2091),
                            Price = 6448.94m,
                            Title = "Refined Concrete Bacon",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(3792),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(3880),
                            Price = 3526.81m,
                            Title = "Sleek Fresh Tuna",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(3900),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(3936),
                            Price = 2246.41m,
                            Title = "Unbranded Rubber Gloves",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(3946),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4044),
                            Price = 3155.01m,
                            Title = "Sleek Plastic Cheese",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4056),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4086),
                            Price = 2967.25m,
                            Title = "Sleek Cotton Computer",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4096),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4125),
                            Price = 5377.74m,
                            Title = "Handcrafted Frozen Ball",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4135),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4164),
                            Price = 660.80m,
                            Title = "Intelligent Metal Car",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4174),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4202),
                            Price = 764.98m,
                            Title = "Ergonomic Concrete Salad",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4211),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4241),
                            Price = 7186.46m,
                            Title = "Sleek Granite Gloves",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4250),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            LastModifiedDate = new DateTime(2023, 6, 29, 13, 17, 4, 469, DateTimeKind.Local).AddTicks(4279),
                            Price = 15.70m,
                            Title = "Intelligent Cotton Keyboard",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Uniqueness", "Email");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 29, 13, 17, 4, 466, DateTimeKind.Local).AddTicks(9661),
                            Email = "example@example.com",
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTimeLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = new byte[] { 170, 104, 132, 8, 161, 9, 37, 255, 51, 5, 254, 108, 81, 167, 59, 131, 81, 234, 198, 236, 54, 98, 217, 37, 254, 84, 125, 151, 233, 69, 109, 60, 213, 10, 30, 219, 119, 124, 70, 198, 105, 130, 114, 226, 223, 118, 134, 176, 171, 246, 136, 208, 27, 244, 221, 114, 105, 59, 82, 233, 168, 106, 44, 5 },
                            PasswordSalt = new byte[] { 33, 111, 223, 95, 30, 54, 139, 202, 199, 100, 76, 105, 209, 183, 148, 75, 117, 128, 44, 146, 31, 96, 102, 33, 144, 108, 202, 77, 181, 57, 104, 147, 60, 193, 215, 146, 172, 118, 140, 152, 55, 182, 212, 126, 73, 49, 49, 82, 67, 168, 28, 130, 251, 195, 186, 126, 127, 151, 220, 25, 98, 176, 32, 41, 185, 160, 25, 4, 68, 240, 59, 139, 96, 124, 220, 76, 55, 171, 132, 217, 68, 28, 160, 35, 139, 142, 156, 229, 179, 210, 204, 4, 226, 42, 52, 21, 15, 191, 6, 113, 77, 55, 123, 217, 68, 0, 233, 73, 151, 123, 3, 204, 162, 150, 127, 119, 146, 100, 173, 75, 111, 106, 203, 169, 70, 48, 189, 80 },
                            isBlocked = false
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("cityScope.NET.Server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
