// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cityScope.NET.Server.Persistence;

#nullable disable

namespace cityScope.NET.Server.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230615173155_SeedAnnouDatabase")]
    partial class SeedAnnouDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(2363),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(4101),
                            Price = 7252.98m,
                            Title = "Licensed Wooden Bike"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5623),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5707),
                            Price = 7253.74m,
                            Title = "Handmade Rubber Chair"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5726),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5758),
                            Price = 440.23m,
                            Title = "Practical Wooden Computer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5767),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5796),
                            Price = 9963.43m,
                            Title = "Tasty Concrete Bike"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5805),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5879),
                            Price = 1915.08m,
                            Title = "Handmade Metal Keyboard"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5887),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5917),
                            Price = 1290.84m,
                            Title = "Incredible Fresh Table"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5925),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5955),
                            Price = 5655.50m,
                            Title = "Ergonomic Plastic Bacon"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5964),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(5992),
                            Price = 6163.67m,
                            Title = "Handcrafted Metal Table"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(6000),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(6028),
                            Price = 7202.43m,
                            Title = "Sleek Soft Table"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(6036),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            LastModifiedDate = new DateTime(2023, 6, 15, 19, 31, 55, 21, DateTimeKind.Local).AddTicks(6062),
                            Price = 9962.86m,
                            Title = "Handcrafted Frozen Sausages"
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
