// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cityScope.NET.Server.Persistence;

#nullable disable

namespace cityScope.NET.Server.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230617113023_ChangeInAnnouncementEntityEfCoreValidation")]
    partial class ChangeInAnnouncementEntityEfCoreValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 691, DateTimeKind.Local).AddTicks(9926),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(1546),
                            Price = 7373.92m,
                            Title = "Unbranded Soft Shirt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3009),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3098),
                            Price = 5944.20m,
                            Title = "Handmade Cotton Car"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3117),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3150),
                            Price = 2361.34m,
                            Title = "Awesome Steel Bike"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3160),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3236),
                            Price = 3495.77m,
                            Title = "Refined Concrete Keyboard"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3246),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3275),
                            Price = 8132.09m,
                            Title = "Licensed Metal Keyboard"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3284),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3313),
                            Price = 4585.90m,
                            Title = "Small Concrete Towels"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3321),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3351),
                            Price = 8064.58m,
                            Title = "Handcrafted Wooden Mouse"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3359),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3390),
                            Price = 3162.46m,
                            Title = "Sleek Steel Pizza"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3399),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3428),
                            Price = 2186.78m,
                            Title = "Licensed Plastic Cheese"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3437),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2023, 6, 17, 13, 30, 23, 692, DateTimeKind.Local).AddTicks(3464),
                            Price = 6116.19m,
                            Title = "Handcrafted Frozen Cheese"
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
