// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cityScope.NET.Server.Persistence;

#nullable disable

namespace cityScope.NET.Server.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230629105110_addDefaultUserAndAddedToAnnouncements")]
    partial class addDefaultUserAndAddedToAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(930),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(1273),
                            Price = 4170.63m,
                            Title = "Handcrafted Rubber Mouse",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3167),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3305),
                            Price = 2704.06m,
                            Title = "Small Soft Bacon",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3328),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3361),
                            Price = 5606.23m,
                            Title = "Small Frozen Computer",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3373),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3404),
                            Price = 6905.93m,
                            Title = "Tasty Frozen Shirt",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3414),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3443),
                            Price = 3099.08m,
                            Title = "Handcrafted Granite Cheese",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3453),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3481),
                            Price = 7810.16m,
                            Title = "Small Metal Pants",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3490),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3522),
                            Price = 9505.44m,
                            Title = "Ergonomic Metal Soap",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3531),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3560),
                            Price = 191.85m,
                            Title = "Intelligent Cotton Chair",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3569),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3599),
                            Price = 4456.99m,
                            Title = "Incredible Fresh Pizza",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3608),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            LastModifiedDate = new DateTime(2023, 6, 29, 12, 51, 10, 405, DateTimeKind.Local).AddTicks(3636),
                            Price = 4696.97m,
                            Title = "Sleek Plastic Towels",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 29, 12, 51, 10, 403, DateTimeKind.Local).AddTicks(45),
                            Email = "example@example.com",
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTimeLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = new byte[] { 89, 230, 85, 104, 118, 145, 154, 123, 80, 103, 230, 243, 218, 252, 86, 52, 69, 200, 129, 211, 245, 133, 40, 22, 120, 78, 30, 215, 162, 242, 243, 161, 35, 130, 15, 65, 96, 30, 151, 180, 13, 6, 190, 206, 104, 115, 21, 236, 127, 87, 15, 225, 214, 138, 52, 14, 166, 50, 193, 237, 153, 7, 31, 62 },
                            PasswordSalt = new byte[] { 2, 162, 173, 90, 108, 187, 26, 81, 87, 66, 32, 203, 243, 67, 20, 155, 208, 250, 180, 250, 99, 141, 223, 53, 165, 77, 59, 77, 78, 162, 3, 4, 200, 116, 35, 113, 197, 249, 104, 226, 174, 189, 111, 248, 8, 132, 73, 24, 76, 95, 65, 98, 51, 149, 124, 90, 206, 133, 252, 107, 102, 220, 54, 37, 140, 83, 32, 23, 97, 239, 19, 98, 27, 0, 45, 174, 141, 36, 220, 56, 177, 48, 214, 147, 184, 228, 216, 119, 78, 180, 52, 160, 168, 143, 63, 219, 2, 92, 135, 40, 177, 11, 76, 113, 232, 109, 136, 152, 64, 43, 80, 176, 224, 205, 194, 130, 129, 158, 58, 87, 170, 141, 124, 241, 220, 130, 244, 235 },
                            isBlocked = false
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("cityScope.NET.Server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
