// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cityScope.NET.Server.Persistence;

#nullable disable

namespace cityScope.NET.Server.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240108145341_AddUserNickName")]
    partial class AddUserNickName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(5264),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(5563),
                            MainCategoryId = 9,
                            Price = 9616.69m,
                            Title = "Rustic Granite Chicken",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/tv.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(7930),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8073),
                            MainCategoryId = 4,
                            Price = 2191.13m,
                            Title = "Small Steel Chicken",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8113),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8166),
                            MainCategoryId = 5,
                            Price = 1672.71m,
                            Title = "Gorgeous Rubber Shirt",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/tv.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8196),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8245),
                            MainCategoryId = 8,
                            Price = 7157.44m,
                            Title = "Incredible Plastic Chicken",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8277),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8338),
                            MainCategoryId = 1,
                            Price = 725.49m,
                            Title = "Tasty Rubber Cheese",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8358),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8399),
                            MainCategoryId = 7,
                            Price = 1848.18m,
                            Title = "Generic Metal Cheese",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8420),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8523),
                            MainCategoryId = 10,
                            Price = 2595.38m,
                            Title = "Unbranded Cotton Bacon",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/table.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8542),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8569),
                            MainCategoryId = 6,
                            Price = 8326.67m,
                            Title = "Intelligent Steel Bacon",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8584),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8609),
                            MainCategoryId = 6,
                            Price = 8581.02m,
                            Title = "Ergonomic Cotton Chair",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/ksiazka.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8623),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2024, 1, 8, 15, 53, 41, 563, DateTimeKind.Local).AddTicks(8651),
                            MainCategoryId = 1,
                            Price = 3492.75m,
                            Title = "Tasty Concrete Computer",
                            UrlImage = "https://blobinz.blob.core.windows.net/images/table.jpg",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MainCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kids"
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountOfAllRates")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Uniqueness", "Email");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("UserDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountOfAllRates = 1,
                            CreatedDate = new DateTime(2024, 1, 8, 15, 53, 41, 559, DateTimeKind.Local).AddTicks(1482),
                            Email = "example@example.com",
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTimeLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NickName = "Michal_Wojciechowski",
                            PasswordHash = new byte[] { 253, 65, 229, 130, 232, 233, 4, 193, 24, 8, 108, 140, 155, 135, 60, 253, 12, 214, 29, 197, 169, 230, 91, 24, 80, 192, 88, 144, 199, 110, 97, 8, 244, 150, 243, 8, 59, 29, 109, 16, 32, 116, 96, 21, 170, 244, 167, 224, 255, 208, 158, 172, 80, 69, 128, 78, 109, 115, 140, 126, 129, 101, 186, 16 },
                            PasswordSalt = new byte[] { 85, 7, 128, 245, 143, 146, 61, 107, 250, 125, 128, 155, 8, 18, 91, 96, 37, 113, 108, 216, 110, 166, 103, 61, 0, 130, 15, 56, 161, 233, 205, 68, 24, 250, 238, 71, 217, 72, 143, 150, 59, 88, 206, 7, 160, 149, 147, 61, 203, 28, 25, 214, 3, 184, 80, 250, 88, 208, 207, 85, 152, 144, 165, 183, 3, 82, 27, 168, 92, 136, 42, 96, 5, 61, 64, 90, 151, 224, 29, 246, 76, 98, 153, 72, 147, 46, 147, 255, 96, 8, 175, 3, 217, 215, 84, 24, 190, 204, 146, 11, 80, 186, 181, 157, 51, 79, 73, 227, 69, 9, 235, 122, 238, 34, 253, 230, 154, 111, 165, 200, 159, 88, 29, 226, 252, 15, 111, 127 },
                            Rate = 5,
                            UserDescription = "odio",
                            isBlocked = false
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("cityScope.NET.Server.Domain.Entities.MainCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cityScope.NET.Server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
