// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cityScope.NET.Server.Persistence;

#nullable disable

namespace cityScope.NET.Server.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 430, DateTimeKind.Local).AddTicks(8939),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(475),
                            Price = 1209.06m,
                            Title = "Incredible Plastic Hat"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2060),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2146),
                            Price = 4474.67m,
                            Title = "Generic Steel Table"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2164),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2199),
                            Price = 4322.29m,
                            Title = "Fantastic Cotton Fish"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2209),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2240),
                            Price = 5028.26m,
                            Title = "Small Cotton Bike"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2249),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2278),
                            Price = 9727.81m,
                            Title = "Ergonomic Cotton Shirt"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2286),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2314),
                            Price = 8698.61m,
                            Title = "Intelligent Rubber Shirt"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2323),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2350),
                            Price = 2630.41m,
                            Title = "Handcrafted Steel Ball"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2358),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2386),
                            Price = 3485.03m,
                            Title = "Handcrafted Wooden Chicken"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2394),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2421),
                            Price = 5817.32m,
                            Title = "Intelligent Metal Cheese"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2429),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            LastModifiedDate = new DateTime(2023, 6, 28, 14, 28, 12, 431, DateTimeKind.Local).AddTicks(2459),
                            Price = 2258.54m,
                            Title = "Licensed Rubber Keyboard"
                        });
                });

            modelBuilder.Entity("cityScope.NET.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
